name: Deploy

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install Mise Dependencies
        uses: jdx/mise-action@v3
      - name: Build LCT
        run: mise run b
      - name: Build Pages
        run: mise run p
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./pages" # The directory containing your static files
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
