name: Tests
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build LCT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Mise Dependencies
        uses: jdx/mise-action@v3
      - name: Build LCT
        run: mise run b
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lct-build
          path: target/build

  test:
    name: Smoke Tests ${{ matrix.shard.index }}/${{ matrix.shard.total }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard:
          - { index: 0, total: 3 }
          - { index: 1, total: 3 }
          - { index: 2, total: 3 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Mise Dependencies
        uses: jdx/mise-action@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lct-build
          path: target/build
      - name: Run Smoke Tests
        env:
          CI_NODE_INDEX: ${{ matrix.shard.index }}
          CI_NODE_TOTAL: ${{ matrix.shard.total }}
        run: bash test/approve
